### ISSUE TITLE
core_riscv32.h is copyright ARM ? Really?

### ISSUE THREAD

**Issue by AnttiLukats** [open-isa-rv32m1/rv32m1_sdk_riscv#2]
it seems weird that file "core_riscv32.h" includes copyright messages saying the author and copyright owner is ARM ?

**Comment by zejiang0jason** [comment]
> it seems weird that file "core_riscv32.h" includes copyright messages saying the author and copyright owner is ARM ?

Hi Antti,

Thank you very much for pointing out this. This is typo because I used a wrong template to generate the header file. This file is not related to ARM.

Thanks.
