### ISSUE TITLE
J-Link Adapter Necessary?

### ISSUE THREAD

**Issue by k0nze** [open-isa-rv32m1/rv32m1_sdk_riscv#3]
Hello,
I followed the instructions to run a demo application on the VEGA-Board. Is a J-Link adapter necessary for running applications on it and if so, which one would you recommend (Linux/macOS)?
Thanks

**Comment by zejiang0jason** [comment]
Hi K0nze,

Sorry for late reply.

JLink adapter is necessary, you can try this: https://www.segger.com/products/debug-probes/j-link/models/j-link-base/. 

Also there are some discussion about this in https://open-isa.org/community/topic/why-do-we-need-an-external-deubgger/. Maybe this helps.

**Comment by k0nze** [comment]
Okay, thanks for the reply.
